spring:
  jpa:
    show-sql: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;mode=mysql
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console